# Generated by Django 2.1.1 on 2018-11-18 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='click_collect.Locality')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='items', to='click_collect.Shop'),
        ),
    ]
