# Generated by Django 2.1.1 on 2018-11-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('click_collect', '0003_auto_20181120_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
