# Generated by Django 2.1.1 on 2018-11-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_collect', '0005_todoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
